<?php
/**
 * @Author: Erhan Kılıç
 * @Website: http://erhankilic.org
 * @Problem: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * https://projecteuler.net/problem=2
 */

// Parameters
$total = 2;
$array = [1, 2];

while (true) {
    $array_count = count($array);
    $sum = $array[$array_count - 1] + $array[$array_count - 2];
    if ($sum < 4000000) {
        $array[] = $sum;
        if ($sum % 2 == 0) {
            $total += $sum;
        }
    } else {
        break;
    }
}
echo $total;